volumes:
  budget-pal:
    external: true
  pg-admin:
    external: true
services:
  postgres:
    image: postgres:14.5-bullseye
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - budget-pal:/var/lib/postgresql/data
    ports:
      - 15432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  fastapi:
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: ${DATABASE_URL}
      CORS_HOST: http://localhost:3000
      WAIT_HOSTS: db:5432
      PORT: 8000
  
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: junghoon_an@email.com
      PGADMIN_DEFAULT_PASSWORD: budget
      PGADMIN_DISABLE_POSTFIX: 1
