volumes:
  budget-pal:
    external: true
services:
  postgres:
    image: postgres:14.5-bullseye
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - budget-pal:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  fastapi:
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: ${DATABASE_URL}
      CORS_HOST: http://localhost:3000
      WAIT_HOSTS: db:5432
      PORT: 8000
  
