FROM python:3.13-bullseye
RUN python3 -m pip install --upgrade pip
WORKDIR /deps

COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt
WORKDIR /app

CMD uvicorn main:app --reload --host 0.0.0.0